//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONET_Exam_Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Addrss { get; set; }
        public string Descript { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderStatusID { get; set; }
        public int CourierID { get; set; }
        public int Price { get; set; }
        public Nullable<int> OrdStatus_OrderID { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual Status Status { get; set; }
    }
}
